package io.github.semenciuccosmin.preferences.factory

/**
 * Factory for creating preferences instances.
 *
 * Two usage patterns are supported:
 * - **KMP projects**: pass a [PreferencesConstructor] generated via
 *   [@ConstructedBy][io.github.semenciuccosmin.preferences.annotations.ConstructedBy].
 *   ```kotlin
 *   val prefs = PreferencesFactory.create(SamplePreferencesConstructor, context)
 *   ```
 * - **Non-KMP Android/JVM projects**: use the reified overload which resolves the
 *   implementation via reflection.
 *   ```kotlin
 *   val prefs = PreferencesFactory.create<SamplePreferences>(context)
 *   ```
 */
object PreferencesFactory

/**
 * Creates a preferences instance using the given [constructor].
 * Recommended for KMP projects.
 *
 * @param T The preferences interface type.
 * @param constructor The [PreferencesConstructor] object (generated by KSP).
 * @param context Platform-specific context required by DataStore.
 *                On Android this is the `Context`; on other platforms it can be `null`.
 * @return A fully initialised instance of [T].
 */
fun <T> PreferencesFactory.create(constructor: PreferencesConstructor<T>, context: Any? = null): T {
    return constructor.initialize(context)
}

/**
 * Creates a preferences instance via reflection by resolving the generated `*Impl` class.
 *
 * Available on Android and JVM targets. On iOS this throws an [IllegalStateException]
 * directing the user to the [PreferencesConstructor]-based overload.
 *
 * Recommended for non-KMP projects where `expect`/`actual` is not available.
 *
 * @param T The preferences interface type.
 * @param context Platform-specific context required by DataStore.
 *                On Android this is the `Context`; on other platforms it can be `null`.
 * @return A fully initialised instance of [T].
 */
expect inline fun <reified T : Any> PreferencesFactory.create(context: Any? = null): T
